TSQL: prevent selectListElem from ignoring valid columns when errorNodes are accumulated
databrickslabs/remorph pull request #1023
Opened 2024-10-25 19:38 UTC by jimidle

In code such as:

```tsql
SELECT col1, , col2 ...
```

Where the parser recovers nicely from the extraneous ',', the visit method woudl ignore the recovery and only return the errorNode output.

Here we use a builder method rather than a visit method and return a Seq[] rather than just a single IR node. The generator then receives all the valid column definitions.

WE also modify the code generator such that it does not add ',' after the generated comments representing error nodes.

2024-10-28 15:32 UTC, vil1 commented on core/src/main/scala/com/databricks/labs/remorph/generators/sql/LogicalPlanGenerator.scala
> +
```suggestion
    val sqlParts = proj.expressions.map { 
      case u: ir.Unresolved[_] => expr.generate(ctx, u)
      case exp: ir.Expression => expr.generate(ctx, exp).map(_ + ", ")
    }
    .mkSql

```

2024-10-28 15:37 UTC, vil1 requested changes
I suggested a change to make things more idiomatic in `project`, but I wonder if expecting an `OkResult` when generating an `Unresolved` is a good idea. My guts say that we shoudl rather return a `PartialResult` in that case (though it might be the point of a future PR). 
In any case, the suggested code will keep working when we make that change.

2024-10-28 15:48 UTC, jimidle commented
> I suggested a change to make things more idiomatic in `project`, but I wonder if expecting an `OkResult` when generating an `Unresolved` is a good idea. My guts say that we shoudl rather return a `PartialResult` in that case (though it might be the point of a future PR). In any case, the suggested code will keep working when we make that change.

Yes - I want to talk about this in the meeting - what is success and what is failure

2024-10-29 17:16 UTC, jimidle commented
> I suggested a change to make things more idiomatic in `project`, but I wonder if expecting an `OkResult` when generating an `Unresolved` is a good idea. My guts say that we shoudl rather return a `PartialResult` in that case (though it might be the point of a future PR). In any case, the suggested code will keep working when we make that change.

Actually, we habve to do a collect after the generate because we want the sqlStr not the OKResult or PartialResult, but I will add that when we change the return type

2024-10-29 21:52 UTC, merged