debug-lineage
databrickslabs/remorph pull request #1050
Opened 2024-11-04 10:54 UTC by sundarshankar89

2024-11-04 11:56 UTC, nfx requested changes

2024-11-04 11:56 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/Main.scala
> +    case Payload("debug-lineage", args) =>
needs changes to `cli.py` and `labs.yml` for this to work.

2024-11-04 11:56 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/graph/TableGraph.scala
> +  def getEdges: Set[Edge] = edges.toSet
```suggestion
  private[graph] val nodes = scala.collection.mutable.Set.empty[Node]
  private[graph] val edges = scala.collection.mutable.Set.empty[Edge]
```

create `GraphvizGenerator` class in the same package as `TableGraph` and use these package-private properties.

2024-11-04 11:56 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/ApplicationContext.scala
> +  }
```suggestion
```

only declarative and dependency-binding code is allowed in `ApplicationContext`.

2024-11-04 11:56 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/Main.scala
> +      val queryHistory = folderQueryHistoryProvider(args("src")).history()
stack this PR on top of https://github.com/databrickslabs/remorph/pull/1051 - there's a fundamental change how we treat the query history.

2024-11-07 05:23 UTC, sundarshankar89 commented
Closing this for now

2024-11-07 05:23 UTC, closed without merging