Source Adapter Init Commit for Reconcile
databrickslabs/remorph pull request #109
Opened 2024-02-05 06:30 UTC by sundarshankar89

Added Source Adapter for Reconcile 

- Extract Data
- Extract Source Schema
- Extract Databricks Schema
- Generate Hash
- Generate Column Transformation

2024-02-05 08:41 UTC, sundarshankar89 commented
@nfx baseline for your review

2024-02-15 17:42 UTC, nfx requested changes

2024-02-15 17:42 UTC, nfx commented on src/databricks/labs/remorph/reconcile/connectors/databricks_connect.py
> +from pyspark.sql import DataFrame
remove `_connect` from these files - it's already clear from the parent folder

2024-02-27 03:38 UTC, sundarshankar89 commented
Tackled by PR #150

2024-02-27 03:38 UTC, closed without merging