[Snowflake] Add support for inline columns in CTEs
databrickslabs/remorph pull request #1184
Opened 2024-11-12 10:18 UTC by vil1

2024-11-12 11:08 UTC, nfx requested changes

2024-11-12 11:08 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/BundleInlineColumnExpressions.scala
> +  private val inlineBundleTable = "INLINE_BUNDLE"
there might be many different names in CTE. Add a new tree node to wrap this name and change the names before they get to codegen.

2024-11-12 11:08 UTC, nfx commented on core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
> +        |    t;""".stripMargin
what about this?
```suggestion
      """WITH
        |    t (d, e) AS (SELECT 4, 5)
        |SELECT
        |    1 + 2,
        |    1 * 2,
        |    1 * t.d
        |FROM
        |    INLINE_BUNDLE,
        |    t;""".stripMargin
```

2024-11-12 11:09 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/BundleInlineColumnExpressions.scala
> +  private val inlineBundleTable = "INLINE_BUNDLE"
and apparently, we don't need this anymore :)

2024-11-12 11:10 UTC, nfx requested changes

2024-11-12 11:10 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/intermediate/extensions.scala
> +case class InlineColumnExpression(columnName: Id, value: Expression) extends LogicalPlan {
```suggestion
private[snowflake] case class InlineColumnExpression(columnName: Id, value: Expression) extends LogicalPlan {
```
and more it to the snowflake folder.

2024-11-13 14:20 UTC, sundarshankar89 approved these changes
LGTM

2024-11-13 14:47 UTC, nfx approved these changes

2024-11-13 14:47 UTC, nfx commented on core/src/test/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspilerTest.scala
> +        |    1 + 2,
nice

2024-11-13 14:47 UTC, merged