add support for SnowFlake SUBSTR
databrickslabs/remorph pull request #1226
Opened 2024-11-20 18:44 UTC by ericvergnaud

SnowFlake supports both SUBSTR and SUBSTRING, see https://docs.snowflake.com/fr/sql-reference/functions/substr.
This PR fills the missing SUBSTR

2024-11-21 09:13 UTC, vil1 requested changes
It looks like `SUBSTRING` wasn't implemented either. 
Looking into `SnowflakeFunctionBuilder` we can see 

```scala
    case "SUBSTR , SUBSTRING" => FunctionDefinition.standard(3)
```
Which appears to be a remnant of the time I scrapped all the function names from the documentation. This malformed definition hasn't been fixed since then, now could be the right time.

If we are certain that `SUBSTR` and `SUBSTRING` will have the same signature in all dialects, we can get rid of that ill-formed definition in SnowflakeFunctionBuilder.

Moreover, to avoid duplicating code in the CallMapper, we can define things like so in the FunctionBuilder:
```scala
case "SUBSTR" => FunctionDefinition.standard(2, 3)
case "SUBSTRING" => FunctionDefinition.standard(2, 3).withConversionStrategy(SynonymOf("SUBSTR"))
```

That way, the CallMapper need only to care about `SUBSTR`.

2024-11-22 09:13 UTC, ericvergnaud commented
> If we are certain that `SUBSTR` and `SUBSTRING` will have the same signature in all dialects, we can get rid of that ill-formed definition in SnowflakeFunctionBuilder.

I would certainly not make that bet

2024-11-22 14:52 UTC, jimidle commented
Tests are not passing - I presume you saw that?

2024-11-22 16:20 UTC, ericvergnaud commented on core/src/test/scala/com/databricks/labs/remorph/parsers/common/FunctionBuilderSpec.scala
> +      ("ABS", FunctionDefinition.standard(1)),
Not sure what we are testing here ? Not behavior. I suggest we get rid of this test altogether...

2024-11-22 16:37 UTC, ericvergnaud commented
> Tests are not passing - I presume you saw that?

Yes, it's fixed now

2024-11-26 10:07 UTC, ericvergnaud commented
Closed in favor of #1238

2024-11-26 10:07 UTC, closed without merging