make changes to Makefile
databrickslabs/remorph pull request #1377
Opened 2024-12-18 10:45 UTC by sundarshankar89

Adds alias in Make command to build Unit and Integration tests.

2024-12-18 14:13 UTC, ericvergnaud requested changes

2024-12-18 14:13 UTC, ericvergnaud commented on Makefile
> +integration-test: setup_spark_remote
maybw rename to `test-integration` ?

2024-12-19 05:48 UTC, bishwajit-db reviewed
Just like unit tests, can we add integration-test-python, integration-test-scala? Later it would be convenient to add Scala integration tests and have uniform target naming convention. In fact, we can then add integration-test-all later to trigger both if needed.

2024-12-19 06:06 UTC, sundarshankar89 commented
> Just like unit tests, can we add integration-test-python, integration-test-scala? Later it would be convenient to add Scala integration tests and have uniform target naming convention. In fact, we can then add integration-test-all later to trigger both if needed.

I have added test-integration and made changes to coverage as well. for now this should be enough considering things we plan to do down the line.

2024-12-19 06:07 UTC, sundarshankar89 commented
@gueniai  need to add mandatory check for `integration-python`

2024-12-19 08:25 UTC, bishwajit-db approved these changes
LGTM

2024-12-30 06:27 UTC, sundarshankar89 commented on Makefile
> +integration-test: setup_spark_remote
Done

2024-12-30 15:20 UTC, ericvergnaud requested changes

2024-12-30 15:20 UTC, ericvergnaud commented on pyproject.toml
> +coverage    = "pytest --cov src tests --cov-report=html"
not sure about this one, do we want to run coverage on both unit and integration tests

2025-01-02 13:48 UTC, sundarshankar89 commented on pyproject.toml
> +coverage    = "pytest --cov src tests --cov-report=html"
Yes, recon uses spark which uses integration tests for coverage. hence this change.

2025-01-03 07:25 UTC, closed without merging