Auto Schema Inference `remorph infer-schema`
databrickslabs/remorph pull request #196
Opened 2024-03-26 15:11 UTC by sundarshankar89

2024-03-27 08:20 UTC, nfx requested changes
Some design flaws

2024-03-27 08:20 UTC, nfx commented on src/databricks/labs/remorph/intermediate/infer_schema.py
> +            create_table_statement = f"CREATE TABLE {table} ({columns_string});"
Use UC APIs to check if tables exists

2024-03-27 08:20 UTC, nfx commented on src/databricks/labs/remorph/intermediate/infer_schema.py
> +            create_table_statement = f"CREATE TABLE {table} ({columns_string});"
Simply because we have to make it unusable outside Databricks

2024-03-27 08:20 UTC, nfx commented on src/databricks/labs/remorph/snow/sql_transpiler.py
> +                        column_table_mapping.setdefault(table_expr.name, []).append(column_expr.name)
Why linter didn't catch this deep nesting?

2024-03-27 08:20 UTC, nfx commented on src/databricks/labs/remorph/snow/sql_transpiler.py
> +                    if table_expr.alias == column_expr.table:
And what if "FROM table AS x JOIN another y USING(foo)"? Make sure there are some good functional tests

2024-03-27 08:20 UTC, nfx commented on tests/unit/intermediate/test_infer_schema.py
> +@pytest.fixture(autouse=True)
```suggestion
@pytest.fixture
```
If it causes issues - it's very difficult to debug

2024-03-27 08:20 UTC, nfx commented on tests/unit/intermediate/test_infer_schema.py
> +        """SELECT a.col1, sum(b.col2) as col2, to_date(col11)
Design is flawed. Our code has to expect a collection of strings and do the work with them. It's the implementation detail where those strings are coming from - files or query history or something else.

Rewrite the tests and implementation

2024-03-27 08:20 UTC, nfx commented on src/databricks/labs/remorph/intermediate/infer_schema.py
> +    def __init__(self, ws: WorkspaceClient, source: str, input_path: str | Path):
```suggestion
    def __init__(self, ws: WorkspaceClient, engine: str):
```

2024-03-27 08:20 UTC, nfx commented on src/databricks/labs/remorph/intermediate/infer_schema.py
> +    def __init__(self, ws: WorkspaceClient, source: str, input_path: str | Path):
Don't tie core logic of how we process queries with how they are stored - we must not have coupling on filesystem and let this core be side-effect free

2024-03-27 08:20 UTC, nfx commented on src/databricks/labs/remorph/snow/sql_transpiler.py
> +    def find_column_table_mapping(self, sql, file_name):
Move this logic to InferSchema, it belongs there

2024-03-27 08:20 UTC, nfx commented on src/databricks/labs/remorph/intermediate/infer_schema.py
> +    def __init__(self, ws: WorkspaceClient, source: str, input_path: str | Path):
File path / folder path should just be arguments for specialized methods

2024-03-27 08:20 UTC, nfx commented on src/databricks/labs/remorph/intermediate/engine_adapter.py
> +    def table_column_mapping(self, sql: str, file_name: str | Path, engine: str) -> dict:
Move to InferSchema

2024-03-27 09:34 UTC, nfx commented on src/databricks/labs/remorph/intermediate/engine_adapter.py
> +    def table_column_mapping(self, sql: str, file_name: str | Path, engine: str) -> dict:
bad:
```
class EngineAdapter:
    def __init__(self, source: str):
        self.source = source
```
good:
```
def create_engine(s, src) -> Adapter:
  if src == "x": return AdaterX(...)
  raise NotImplemented(...)
```

2024-03-27 09:38 UTC, nfx commented on src/databricks/labs/remorph/intermediate/infer_schema.py
> +class InferSchema:
```suggestion
class InferSchemaViaSqlGlot:
```

2024-03-27 09:42 UTC, nfx commented on src/databricks/labs/remorph/intermediate/infer_schema.py
> +    def generate_schema(self, engine: str = "sqlglot") -> dict:
```suggestion
    def generate_schema(self) -> dict:
```

2024-05-27 05:31 UTC, sundarshankar89 commented
closing for now, will handle it later.

2024-05-27 05:31 UTC, closed without merging