Creates the jump off point for creating IR from the TSQL parse tree walker
databrickslabs/remorph pull request #286
Opened 2024-04-26 14:24 UTC by jimidle

This is the starting point for new feature issue #275

2024-04-26 14:44 UTC, vil1 reviewed
This looks like duplicate in respect with #267

2024-04-26 18:06 UTC, jimidle commented
> This looks like duplicate in respect with #267

Yes - I did search but that did not come up as it seemed like the start of the SELECT statement, and there was no code for TSQL in main at that point. However, this issue will cover more basic elements. We won't get very far into the SELECT statement before we need all the more primitive elements of an expression.

2024-04-27 10:56 UTC, nfx requested changes

2024-04-27 10:56 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/expressions.scala
> +    real: Option[String] = None,
Changing this is not allowed - it's generated from protobuf. Use double

2024-04-27 10:56 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +    ctx match {
From our scala style:

For method whose entire body is a pattern match expression, put the match on the same line as the method declaration if possible to reduce one level of indentation.

2024-04-27 10:56 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +    ctx match {
Please read this (whole) document again: https://github.com/databricks/scala-style-guide?tab=readme-ov-file#pattern-matching

2024-04-27 10:56 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +    val sym = node.getSymbol
Do we need this constant?..

2024-04-27 16:05 UTC, nfx approved these changes
Lgtm

2024-04-27 16:06 UTC, merged