TSQL `Join` Expressions
databrickslabs/remorph pull request #298
Opened 2024-04-30 11:26 UTC by sundarshankar89

2024-04-30 13:54 UTC, sundarshankar89 commented
[TODO]: Need to address Table alias and Column alias.

2024-04-30 15:07 UTC, jimidle requested changes
I feel this is incomplete give the Or and Not are essentially the same thing. Grammar change is OK, but the whole search_condition might get revisited down the line.

2024-04-30 15:07 UTC, jimidle commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
Implement Or and Not

2024-04-30 15:15 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +  }
I think I added a TODO in visitPredicate, if not I might have missed it.

2024-04-30 15:15 UTC, sundarshankar89 commented on core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
>      ;
Yes

2024-04-30 15:15 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
I missed a TODO

2024-04-30 15:40 UTC, vil1 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +  }
You may want your class to extend `IncompleteParser` (it will automatically wrap the parse tree in a `UnresolvedSomething` of your choice)

2024-05-01 12:21 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +    operator match {
we need to scala style for this, so we can be consistent.

2024-05-01 13:35 UTC, nfx approved these changes
lgtm

2024-05-01 13:35 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +        ir.Not(ctx.predicate().accept(this))
```suggestion
    } else {
      if (!ctx.NOT().isEmpty) {
        ir.Not(ctx.predicate().accept(this))
```

2024-05-01 13:35 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +
```suggestion
```

2024-05-01 13:35 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
> +  private def buildJoin(left: ir.Relation, right: Join_partContext): ir.Join = {
```suggestion

  private def buildJoin(left: ir.Relation, right: Join_partContext): ir.Join = {
```

2024-05-02 04:10 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlRelationBuilder.scala
> +  private def buildJoin(left: ir.Relation, right: Join_partContext): ir.Join = {
Fixed ran Make fmt

2024-05-02 04:11 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +
Fixed ran make fmt

2024-05-02 04:11 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +        ir.Not(ctx.predicate().accept(this))
make fmt

2024-05-02 04:11 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +  }
Done

2024-05-02 04:11 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
> +  }
I have implemented NOT

2024-05-02 04:17 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/tsql/TSqlExpressionBuilder.scala
Done

2024-05-02 08:37 UTC, sundarshankar89 commented
@jimidle fixed your comments ready for review

2024-05-02 13:59 UTC, nfx approved these changes
lgtm

2024-05-02 13:59 UTC, merged