Add IR builder for Tsql Unary expressions
databrickslabs/remorph pull request #300
Opened 2024-04-30 18:13 UTC by alti-tude

2024-04-30 18:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/databrickslabs/remorph?pullRequest=300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/databrickslabs/remorph?pullRequest=300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/databrickslabs/remorph?pullRequest=300) it.</sub>

2024-05-01 13:41 UTC, nfx approved these changes
@jimidle do we need this one?..

2024-05-01 13:41 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/extensions.scala
> +object Minus {
we had a change to this in the other PRs, please rebase and resolve conflicts

2024-05-03 13:36 UTC, jimidle requested changes
Unary constructs should use names that imply they are unary. UMinus and UPlus for instance. Also, they should be case classes extending Unary in `extensions.scala`.

As i will change the grammar to deal with unary correctly, this PR will be obsoleted and I am sorry to say it is better to start again than be misguided by the current grammar.

@alti-tude Sorry mate, but would you please just close this one.

2024-05-04 04:34 UTC, jimidle commented
> @jimidle do we need this one?..

No. the PR was misguided by the state of the grammar. We can close this now as my other PRs implement this with grammar changes

2024-05-21 13:08 UTC, closed without merging

2024-05-21 13:09 UTC, jimidle commented
Closed as already implemented.