Provide a rudimentary error collector for syntax errors and future semantic and linting errors
databrickslabs/remorph pull request #346
Opened 2024-05-13 20:38 UTC by jimidle

A simple error collector is created, which allows determination of errors in test code and makes that a little easier. In the future, it can be expanded to support different types of errors such as semantic errors.

Closes: #340

2024-05-13 20:48 UTC, jimidle commented
@sundarshankar89 - Reworked to use Log4j as supplied by scala-core

2024-05-14 08:41 UTC, vil1 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/ErrorCollector.scala
> +  def formatErrors(): Seq[String] = {
```suggestion
  private [parsers] def formatErrors: Seq[String] = {
```

2024-05-14 08:41 UTC, vil1 commented on core/src/main/scala/com/databricks/labs/remorph/parsers/ErrorCollector.scala
> +    val formattedErrors = formatErrors()
```suggestion
    val formattedErrors = formatErrors
```

2024-05-14 08:42 UTC, vil1 requested changes
A few comments and suggestions.

2024-05-14 14:09 UTC, jimidle commented on core/src/test/scala/com/databricks/labs/remorph/parsers/ParserTestCommon.scala
> +  protected def makeErrHandler(chars: String): ErrorCollector = null
Default handler created for sealed trait

2024-05-17 15:58 UTC, jimidle commented
> A few comments and suggestions.

All addressed now I think? Seems I cannot mark as resolved.

2024-05-22 05:42 UTC, merged