Add full support for analytical windowing functions
databrickslabs/remorph pull request #401
Opened 2024-05-28 19:36 UTC by jimidle

Analytical windowing functions were specified in the grammar instead of our standard function lookup table.

These functions are now removed from the parser grammar and specified in the standard tables.

Additionally,  the WITHIN GROUP syntax is supported using an additional `expression` rule alt. This makes function handling orthogonal for all but the so called `builtinFunctions` 

We now support analytical aggregate functions as evinced by the following examples:

```sql
... FIRST_VALUE(Salary) OVER (PARTITION BY DepartmentID ORDER BY Salary DESC)
``` 

```sql
... PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY Salary) OVER (PARTITION BY DepartmentID)
```

2024-05-29 16:04 UTC, vil1 commented on core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
> +//    example(
Please uncomment/remove this

2024-05-29 16:06 UTC, vil1 requested changes
LGTM, minus some commented out code that snuck in.

2024-05-29 17:20 UTC, jimidle commented on core/src/test/scala/com/databricks/labs/remorph/parsers/tsql/TSqlFunctionSpec.scala
> +//    example(
Too many PRs at once :)

2024-05-30 12:49 UTC, jimidle commented
> LGTM, minus some commented out code that snuck in.

@vil1 If you coudl mark the changes as resolved, then @sundarshankar89 can add this to the merge queue - cheers.

2024-06-03 16:21 UTC, nfx approved these changes
lgtm

2024-06-03 19:08 UTC, merged