Intermediate cache to volumes
databrickslabs/remorph pull request #429
Opened 2024-06-04 11:04 UTC by ganeshdogiparthi-db

2024-06-04 14:42 UTC, nfx requested changes

2024-06-04 14:42 UTC, nfx commented on src/databricks/labs/remorph/reconcile/compare.py
> +        .drop(f"{_HASH_COLUMN_NAME}")
```suggestion
        .drop(_HASH_COLUMN_NAME)
```
F-string is redundant here

2024-06-05 03:53 UTC, ganeshdogiparthi-db commented on src/databricks/labs/remorph/reconcile/compare.py
> +        .drop(f"{_HASH_COLUMN_NAME}")
Done

2024-06-05 13:59 UTC, sundarshankar89 requested changes

2024-06-05 13:59 UTC, sundarshankar89 commented on src/databricks/labs/remorph/reconcile/recon_capture.py
> +def write_and_read_unmatched_df_with_volumes(
```suggestion
def read_and_write_unmatched_df_with_volumes(
```

2024-06-05 14:41 UTC, sundarshankar89 approved these changes
LGTM

2024-06-06 17:05 UTC, nfx approved these changes

2024-06-06 17:09 UTC, merged