Added the missing info for the reconciliation documentation
databrickslabs/remorph pull request #520
Opened 2024-07-02 13:54 UTC by ravit-db

2024-07-03 04:15 UTC, ganeshdogiparthi-db requested changes

2024-07-03 04:15 UTC, ganeshdogiparthi-db commented on README.md
> +recon_config_databricks_catalog_all.json
eg:
SOURCE: databricks
CATALOG_OR_SCHEMA: curated
REPORT_TYPE: all
recon_config_databricks_curated_all.json
eg:
SOURCE: snowflake
CATALOG_OR_SCHEMA: sales_catalog
REPORT_TYPE: row
recon_config_snowflake_sales_catalog_row.json

try to give more examples

2024-07-10 08:25 UTC, ganeshdogiparthi-db approved these changes
LGTM

2024-07-10 08:34 UTC, nfx approved these changes

2024-07-10 08:34 UTC, merged