Feature/support tsql ctas in grammar
databrickslabs/remorph pull request #545
Opened 2024-07-11 08:32 UTC by bishwajit-db

Support CTAS in TSQL Grammar.
Support for != operator

2024-07-17 11:43 UTC, nfx requested changes

2024-07-17 11:43 UTC, nfx commented on core/src/main/antlr4/com/databricks/labs/remorph/parsers/tsql/TSqlParser.g4
> +    | CREATE TABLE tableName (LPAREN columnNameList RPAREN)? tableOptions? AS selectStatementStandalone SEMI?
create two rules - `createTableDefault` and `createTableAs`. this will simplify the parser. add unit and functional tests

2024-07-22 09:15 UTC, bishwajit-db commented
@jimidle, could you please take over the PR so that the changes can be included along with DDLBulider for TSQL?

2024-07-24 08:16 UTC, nfx commented
@bishwajit-db Jim will pick it up after vacation

2024-07-24 15:50 UTC, jimidle commented
> @bishwajit-db Jim will pick it up after vacation

The CREATE TABLE grammar will need quite a lot of changes, as it is still in the style of the original grammar we had, but the operator stuff looks fine in the current way they are being handled - those operators were obviously missed originally. That grammar form is possibly going to change, but I will make sure to include these operators if I change it.

2024-07-24 19:40 UTC, jimidle commented
@nfx This PR can be merged as-is, as the operators were just missing from the original grammar and the changes to CREATE TABLE are innocuous. There will be significant changes to CREATE once I start on it as there is more missing than CTAS and as CREATE xxx is expressed it will cause ANTLR to do a lot of lookahead to predict the correct alts. Changing the whole of create is a series of additional PRs.

2024-07-24 19:41 UTC, jimidle approved these changes
lgtm

2024-07-25 14:03 UTC, merged