Added logger statements in get_schema
databrickslabs/remorph pull request #756
Opened 2024-08-01 16:02 UTC by vijaypavann-db

Added logger statements in Metadata (Schema) fetch functions.
* logging `Schema Query`, `start time` and `end time`.

2024-08-02 02:12 UTC, sundarshankar89 requested changes

2024-08-02 02:12 UTC, sundarshankar89 commented on src/databricks/labs/remorph/reconcile/connectors/snowflake.py
> +            logger.warning(f"Fetching Schema: Started at: {datetime.now()}")
```suggestion
            logger.info(f"Fetching Schema: Started at: {datetime.now()}")
```
change it to info for both.

2024-08-02 06:20 UTC, sundarshankar89 requested changes
Small nit:

2024-08-02 06:20 UTC, sundarshankar89 commented on src/databricks/labs/remorph/reconcile/connectors/snowflake.py
> +    @timeit
Don't add `timeit` here

2024-08-04 14:05 UTC, vijaypavann-db commented on src/databricks/labs/remorph/reconcile/connectors/snowflake.py
> +    @timeit
Done

2024-08-04 14:48 UTC, vijaypavann-db commented
Snowflake documentation doesn't describe any user-configurable partitioning or clustering for Information Schema views. These views appear to be system-managed and optimized by Snowflake internally.

* Partitioning
  https://docs.snowflake.com/en/sql-reference/info-schema#considerations-for-replacing-show-commands-with-information-schema-views
  "The Information Schema views are optimized for queries that retrieve a small subset of objects from the dictionary. Whenever possible, maximize the performance of your queries by filtering on schema and object names."

* Data 
  https://docs.snowflake.com/en/sql-reference/identifiers-syntax#double-quoted-identifiers
  
  - Only unquoted identifiers are treated as case-insensitive and are stored in uppercase in INFORMATION_SCHEMA
  - Quoted identifiers are stored as it is:
   
    <img width="584" alt="image" src="https://github.com/user-attachments/assets/e5b8d0ab-e2c4-4ffc-8f2e-46f65b5cfe10">

    **In our codebase, we're trying to convert the Schema to uppercase which may not work for the cases like above.**
    `SnowflakeDataSource._SCHEMA_QUERY.format(catalog=catalog, schema=schema.upper(), table=table)`

   - Schema converted to Upper Case: 
     <img width="858" alt="image" src="https://github.com/user-attachments/assets/3c0e0819-d214-4cd2-b137-556707559b22">

   - The same is applicable for Table Identifier as well: 
     <img width="713" alt="image" src="https://github.com/user-attachments/assets/14fe9a2b-3ece-4656-9234-474aec8befe2">

  - Lower Table doesn't work: 
     <img width="788" alt="image" src="https://github.com/user-attachments/assets/8e66ac03-7353-4731-8a58-861c9bfc70b3">

2024-08-05 03:57 UTC, sundarshankar89 submitted a review, later dismissed
LGTM

2024-08-07 01:34 UTC, sundarshankar89 requested changes

2024-08-07 01:34 UTC, sundarshankar89 commented on src/databricks/labs/remorph/config.py
> +        self.source_schema = (
We need this revisited.

2024-08-07 05:25 UTC, vijaypavann-db commented on src/databricks/labs/remorph/config.py
> +        self.source_schema = (
If the user-provided input contains any special characters, we could escape them with `backticks`, but what if the catalog is created with quoted identifiers, e.g., "lowercase_catalog," and it's stored as it is (lowercase) in the INFORMATION_SCHEMA?

If we handle the user input with escape characters in the codebase, we would miss these kinds of cases.

2024-08-07 09:28 UTC, vijaypavann-db commented on src/databricks/labs/remorph/reconcile/connectors/snowflake.py
> +    _SCHEMA_QUERY = """select column_name,
Done

2024-08-07 14:44 UTC, sundarshankar89 approved these changes
LGTM

2024-08-12 09:54 UTC, merged