Handling window frame of rank-related functions in snowflake
databrickslabs/remorph pull request #833
Opened 2024-08-21 12:44 UTC by ganeshdogiparthi-db

closes #782

2024-08-21 14:21 UTC, nfx requested changes
still failing tests:

lag_1.sql:
```
LAG: illegal index: 1, expr: CallFunction LAG
+- Id col1, false
```

last_value_2.sql
```
NullPointerException: null
```

lead_1.sql
```
LEAD: illegal index: 1, expr: CallFunction LEAD
+- Id col1, false
```

nth_value_3.sql
```
NullPointerException: null
```

2024-08-21 14:22 UTC, nfx commented on tests/resources/functional/snowflake/functions/window/last_value_2.sql
> +
remove leading blank line. looks messy

2024-08-21 14:23 UTC, nfx commented on tests/resources/functional/snowflake/aggregates/test_dense_rank_2.sql
> +
remove leading blank lines from all example files. looks unprofessional.

2024-08-21 14:23 UTC, nfx commented on tests/resources/functional/snowflake/aggregates/test_dense_rank_2.sql
> +SELECT DENSE_RANK() OVER (PARTITION BY col1 ORDER BY col2 DESC NULLS FIRST RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS dense_rank_col1 FROM tabl;
pretty-print queries/translated examples. use `pretty=True` when generating them

2024-08-23 02:41 UTC, ganeshdogiparthi-db commented on tests/resources/functional/snowflake/aggregates/test_dense_rank_2.sql
> +SELECT DENSE_RANK() OVER (PARTITION BY col1 ORDER BY col2 DESC NULLS FIRST RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS dense_rank_col1 FROM tabl;
Done

2024-08-23 02:41 UTC, ganeshdogiparthi-db commented on tests/resources/functional/snowflake/aggregates/test_dense_rank_2.sql
> +
Done

2024-08-23 02:41 UTC, ganeshdogiparthi-db commented on tests/resources/functional/snowflake/functions/window/last_value_2.sql
> +
Done

2024-08-23 02:41 UTC, ganeshdogiparthi-db commented on tests/resources/functional/snowflake/functions/window/nth_value_3.sql
> +SELECT tabb.col_a, tabb.col_b, NTH_VALUE(CASE WHEN tabb.col_c IN (‘xyz’, ‘abc’) THEN tabb.col_d END, 42) IGNORE NULLS OVER (PARTITION BY tabb.col_e ORDER BY tabb.col_f DESC NULLS FIRST RANGE BETWEEN
Done

2024-08-23 10:09 UTC, nfx approved these changes
lgtm

2024-08-23 10:09 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/functions.scala
> +    // case CallFunction("LAG", args) => Lag(args.head, args(1), args(2))
```suggestion
```

2024-08-23 10:09 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/functions.scala
> +    // case CallFunction("LEAD", args) => Lead(args.head, args(1), args(2))
```suggestion
```
remove commented code

2024-08-23 10:40 UTC, merged