Legacy/fix lateral struct test
databrickslabs/remorph pull request #865
Opened 2024-08-28 16:46 UTC by aman-db

close #848

2024-09-10 19:02 UTC, sundarshankar89 requested changes

2024-09-10 19:02 UTC, sundarshankar89 commented on tests/resources/functional/snowflake/ddl/lateral_struct/test_lateral_struct_10.sql
> +LATERAL VIEW EXPLODE(FROM_JSON(tt.resp, schema_of_json('tt.resp')).order.items) AS lit
```suggestion
LATERAL VIEW EXPLODE(FROM_JSON(tt.resp, schema_of_json('{{TT.RESP_SCHEMA}}')).order.items) AS lit
```

2024-10-07 10:58 UTC, sundarshankar89 commented
@aman-db Can this PR be closed?

2024-10-07 11:22 UTC, aman-db commented
> @aman-db Can this PR be closed?

yes, this is not required. this will be addressed by #894

2024-10-08 09:51 UTC, closed without merging