Add T-SQL validation queries
databrickslabs/remorph pull request #876
Opened 2024-09-02 11:08 UTC by bishwajit-db

Add T-SQL validation queries.  Resolves #636

2024-09-03 13:09 UTC, sundarshankar89 requested changes
I would prefer to have meaningful filenames

2024-09-16 14:25 UTC, bishwajit-db commented
> I would prefer to have meaningful filenames

Yes, that would be better. Right now, it just uses the example file name. However, it will make the process more complex and require another LLM inference step to generate the filenames based on the content. Can we skip it unless absolutely required?

2024-11-27 14:24 UTC, jimidle commented
> > I would prefer to have meaningful filenames
> 
> Yes, that would be better. Right now, it just uses the example file name. However, it will make the process more complex and require another LLM inference step to generate the filenames based on the content. Can we skip it unless absolutely required?

I think it is OK to leave this - it is already a massive PR because of the huge number of examples.

2024-11-27 14:26 UTC, jimidle approved these changes
It's impossible to check all examples in a review but that is just how it has to be unfortunately.

2024-11-27 16:40 UTC, gueniai commented
@bishwajit-db I've made a note on the issue so that we have a placeholder to add the Databricks version of all of these, so that we can go ahead and merge this and then work on the other part on a separate PR.

2024-12-13 14:42 UTC, jimidle approved these changes
LGTM - mechanical change

2024-12-13 18:50 UTC, vil1 approved these changes
lgtm

2025-01-02 13:46 UTC, sundarshankar89 commented
@bishwajit-db closing this PR and will delete the branch.

2025-01-02 13:46 UTC, closed without merging