Create more robust toolchain control with error recording for repeatable testing
databrickslabs/remorph pull request #888
Opened 2024-09-04 21:29 UTC by jimidle

Here, we extend the basic toolchain we had such that all errors are captured and errors at any stage in the workflow `parse->visit->optimize->transpile` prevent an attempt to continue the workflow. This prevents, for example, attempts to generate IR from a parse tree generated with syntax errors. There is no point trying to generate IR from a broken ParseTree.

We also provide some basic source code providers for directories and files. 

Finally, we provide a command line interface for transpilation such that developers can look at the results of any particular input. This includes the ability to retrieve query history (Snowflake only for now), attempt to compile each retrieved query and record the results as jsonl output. The code the command line uses can be the basis for an ongoing integration test further down the line.

2024-09-18 16:58 UTC, nfx requested changes
use PlanParser abstractions that are already there

2024-09-19 21:32 UTC, jimidle commented on core/src/main/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspiler.scala
> +      Result(stage = WorkflowStage.PLAN, plan = Some(plan), tree = tree.tree)
Changed to use Monads

2024-09-19 21:33 UTC, jimidle commented on core/src/main/scala/com/databricks/labs/remorph/transpilers/SnowflakeToDatabricksTranspiler.scala
> +      Result(stage = WorkflowStage.PARSE, errorsJson = errListener.errorsAsJson, tree = Some(tree))
Changed to use Monads

2024-09-20 13:03 UTC, nfx reviewed
i'll issue follow-up refactorings

2024-09-20 13:04 UTC, merged