Improve translation of LATERAL FLATTEN
databrickslabs/remorph pull request #891
Opened 2024-09-06 07:51 UTC by vil1

2024-09-06 16:28 UTC, nfx requested changes

2024-09-06 16:28 UTC, nfx commented on core/src/main/antlr4/com/databricks/labs/remorph/parsers/snowflake/SnowflakeParser.g4
> +
```suggestion
temporalExpr
    : functionCall 
    | primitiveExpression
	;

```

blank lines are eye sores

2024-09-06 16:28 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/intermediate/plans.scala
> +  def nestedExpressions: Seq[Expression] = {
why do we need to modify a widely-used class with the method that's used only once?

2024-09-06 16:28 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/FlattenLateralViewToExplode.scala
> +
```suggestion
```
i wonder why scalafmt doesn't pick it up

2024-09-06 16:28 UTC, nfx commented on core/src/main/scala/com/databricks/labs/remorph/parsers/snowflake/rules/FlattenLateralViewToExplode.scala
> +    val translatedToExplode = plan transform {
fun one, right?

2024-09-06 16:29 UTC, nfx commented
@vil1 also fix py failures

2024-09-27 11:51 UTC, vil1 commented
Will be done by @aman-db in another PR

2024-09-27 11:51 UTC, closed without merging