Table comments captured as part of Snowflake Table Definition
databrickslabs/remorph pull request #949
Opened 2024-10-03 11:54 UTC by sriram251-code

closes #945 

This pull request involve adding support for table comments, modifying the `TableDefinition` case class, and introducing a new integration test for Snowflake table definitions.

2024-10-03 14:54 UTC, nfx approved these changes
lgtm

2024-10-09 06:52 UTC, sriram251-code commented
The code is dependent on https://github.com/databrickslabs/remorph/pull/923 . Once https://github.com/databrickslabs/remorph/pull/923 is merged then we can merge this PR.

2024-10-10 08:54 UTC, sundarshankar89 requested changes

2024-10-10 08:54 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/discovery/SnowflakeTableDefinitions.scala
> +       |    LISTAGG(column_name || '§' ||
can we move to `~`? This is a common un-conflicting delimiter instead of a Multibyte delimiter?

2024-10-10 10:17 UTC, sundarshankar89 approved these changes
LGTM

2024-10-10 10:17 UTC, sundarshankar89 commented on core/src/main/scala/com/databricks/labs/remorph/discovery/SnowflakeTableDefinitions.scala
> +       |    LISTAGG(column_name || '§' ||
makes sense.

2024-10-10 10:34 UTC, merged